base_url = "https://www.katsaii.com/lounging"
ring_name = "Loungeware Collective"
ring_description = "A webring to add something cool to later."
ring_owner = "Katsaii"
ring_owner_site = "https://www.katsaii.com"

filepath_list = "./websites.toml"   # Website list; should be a JSON or TOML file with 'name', 'url', etc 
path_output = "./webring"           # Generated files will be saved in this folder.
path_assets = "./data/assets"       # All contents of the asset folder will be copied directly into the output directory
path_templates = "./data/templates" # The folder containing HTML templates to use, ie, anything with {{ tags }}
filename_template_random = "random.html" # This template is used for random redirect feature.
filename_template_redirect = "redirect.html" # This template gets reused to build the redirect pages for each site, and is ignored when building the other custom templates

client_user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
client_header = "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
audit_retries_delay = 100
audit_retries_max = 2

shuffle = true          # Randomizes website sequence when generating
verbose = false         # Enables verbose logging
skip_minify = false     # If your generated HTML have issues, or you want hand-editable output, try skip minification
skip_verify = false     # Skips verification of the URLs in the list. Might be unwise!
dry_run = false         # Perform a dry run without writing any files. Can be used to check the site audit for example. 
