[[websites]]
name = "Katsaii Homepage"
slug = "katsaii"
about = "Home of the Katsaii nation."
url = "https://www.katsaii.com/"
owner = "katsaii"

[[websites]]
name = "Mashmerlow Homepage"
slug = "mashmerlow"
about = "Failgirl extraordinaire."
url = "https://mashmerlow.art/#links"
owner = "mashmerlow"

[[websites]]
name = "Net8floz Homepage"
slug = "net8floz"
about = "The catman."
url = "https://net8floz.loungeware.games/"
owner = "net8floz"

[[websites]]
name = "Baku Homepage"
slug = "baku"
about = "Game Girl Advance."
url = "http://baku.dk/"
owner = "baku"